with open('js/data_libros.js', 'r', encoding='utf-8', errors='replace') as f:
    content = f.read()

modules = content.count('bookNumber:')
pillars = content.count('tacticalRule:')
flashcards = content.count("id: 'fc")
quizzes = content.count("id: 'q")
scenarios = content.count('scenarioDescription:')
matrix = content.count('counterScript:')
bodylab = content.count('practicalDrill:')
glossary = content.count('definition:')
diagrams = content.count('diagram:')
challenges = content.count('interactiveChallenge:')

print('DATA AUDIT:')
print('Modules:', modules)
print('Key Pillars:', pillars)
print('Flashcards:', flashcards)
print('Quizzes:', quizzes)
print('Scenarios:', scenarios)
print('Matrix cards:', matrix)
print('BodyLab entries:', bodylab)
print('Glossary terms:', glossary)
print('Diagrams:', diagrams)
print('Interactive Challenges:', challenges)
print('File size:', round(len(content)/1024, 1), 'KB')
