import os
import re
import json

MD_DIR = 'Psicologia_Oscura'
BOOK_JS = 'js/book_content.js'

print("=== MOTOR LINGUISTICO LOCAL: RECONSTRUCCION TOTAL Y CORRECCION RAE ===")

# DICCIONARIO MAESTRO DE TRANSFORMACIONES LÉXICAS, ORTOGRÁFICAS Y MORFOLÓGICAS
RULES = [
    # 1. AUTOR Y METADATOS PEGADOS
    (r'\b\*{0,3}###\s*Por Benedict Goleman\*{0,3}\s*([A-ZÁÉÍÓÚa-z])', r'### Autor: Benedict Goleman\n\n\1'),
    (r'\b\*{0,3}BENEDICT GO[EL]{2}MAN\*{0,3}\s*([A-ZÁÉÍÓÚa-z])', r'### Autor: Benedict Goleman\n\n\1'),
    (r'\bBENEDICT GO[EL]{2}MAN\b', '### Autor: Benedict Goleman'),
    (r'\bBenedict Goleman([A-ZÁÉÍÓÚ])', r'Benedict Goleman\n\n\1'),
    (r'\bused\b', 'usted'),
    (r'\bUsed\b', 'Usted'),
    (r'\bal al\b', 'al'),
    (r'\bparal que\b', 'para el que'),
    (r'\bdejar aal\b', 'dejar al'),

    # 2. RESTAURACIÓN DE LA LETRA 'Ñ'
    (r'\banos\b', 'años'),
    (r'\bAnos\b', 'Años'),
    (r'\bano\b', 'año'),
    (r'\bAno\b', 'Año'),
    (r'\bninos\b', 'niños'),
    (r'\bNinos\b', 'Niños'),
    (r'\bnino\b', 'niño'),
    (r'\bNino\b', 'Niño'),
    (r'\bnina\b', 'niña'),
    (r'\bNina\b', 'Niña'),
    (r'\bninas\b', 'niñas'),
    (r'\bNinas\b', 'Niñas'),
    (r'\bdano\b', 'daño'),
    (r'\bDano\b', 'Daño'),
    (r'\bdanos\b', 'daños'),
    (r'\bDanos\b', 'Daños'),
    (r'\bdanino\b', 'dañino'),
    (r'\bdanina\b', 'dañina'),
    (r'\bdaninos\b', 'dañinos'),
    (r'\bdaninas\b', 'dañinas'),
    (r'\bengano\b', 'engaño'),
    (r'\bEngano\b', 'Engaño'),
    (r'\benganos\b', 'engaños'),
    (r'\bEnganos\b', 'Engaños'),
    (r'\benganar\b', 'engañar'),
    (r'\benganan\b', 'engañan'),
    (r'\benganado\b', 'engañado'),
    (r'\benganada\b', 'engañada'),
    (r'\benganoso\b', 'engañoso'),
    (r'\benganosa\b', 'engañosa'),
    (r'\btamano\b', 'tamaño'),
    (r'\bTamano\b', 'Tamaño'),
    (r'\btamanos\b', 'tamaños'),
    (r'\bpequeno\b', 'pequeño'),
    (r'\bPequeno\b', 'Pequeño'),
    (r'\bpequena\b', 'pequeña'),
    (r'\bPequena\b', 'Pequeña'),
    (r'\bpequenos\b', 'pequeños'),
    (r'\bPequenos\b', 'Pequeños'),
    (r'\bpequenas\b', 'pequeñas'),
    (r'\bPequenas\b', 'Pequeñas'),
    (r'\bensenaba\b', 'enseñaba'),
    (r'\bensenaban\b', 'enseñaban'),
    (r'\bensenar\b', 'enseñar'),
    (r'\bensenanza\b', 'enseñanza'),
    (r'\bensenanzas\b', 'enseñanzas'),
    (r'\bcompania\b', 'compañía'),
    (r'\bcompanias\b', 'compañías'),
    (r'\bcompanero\b', 'compañero'),
    (r'\bcompanera\b', 'compañera'),
    (r'\bcompaneros\b', 'compañeros'),
    (r'\bcompaneras\b', 'compañeras'),
    (r'\bresena\b', 'reseña'),
    (r'\bresenas\b', 'reseñas'),
    (r'\bsenales\b', 'señales'),
    (r'\bSenales\b', 'Señales'),
    (r'\bsenal\b', 'señal'),
    (r'\bSenal\b', 'Señal'),
    (r'\bsenalar\b', 'señalar'),
    (r'\bsenala\b', 'señala'),
    (r'\bsenalan\b', 'señalan'),
    (r'\bsenalaron\b', 'señalaron'),
    (r'\bsenalado\b', 'señalado'),
    (r'\bdueno\b', 'dueño'),
    (r'\bduena\b', 'dueña'),
    (r'\bsueno\b', 'sueño'),
    (r'\bsuenos\b', 'sueños'),
    (r'\bpunos\b', 'puños'),
    (r'\bpuno\b', 'puño'),
    (r'\bcarino\b', 'cariño'),
    (r'\bcarinoso\b', 'cariñoso'),
    (r'\bcarinosa\b', 'cariñosa'),
    (r'\bdiseno\b', 'diseño'),
    (r'\bDiseno\b', 'Diseño'),
    (r'\bdisenos\b', 'diseños'),
    (r'\bdisenados\b', 'diseñados'),
    (r'\bdisenado\b', 'diseñado'),
    (r'\bdisenada\b', 'diseñada'),
    (r'\bdisenadas\b', 'diseñadas'),

    # 3. ERRATAS SISTEMÁTICAS DE DIGITALIZACIÓN OCR
    (r'\bP\*{3,4}SICOLOGIA\b', 'PSICOLOGÍA'),
    (r'\bpiscologia\b', 'psicología'),
    (r'\bPiscologia\b', 'Psicología'),
    (r'\bpscicologia\b', 'psicología'),
    (r'\bPscicologia\b', 'Psicología'),
    (r'\bpiscologos\b', 'psicólogos'),
    (r'\bPiscologos\b', 'Psicólogos'),
    (r'\bpiscologica\b', 'psicológica'),
    (r'\bPiscologica\b', 'Psicológica'),
    (r'\bpiscologico\b', 'psicológico'),
    (r'\bPiscologico\b', 'Psicológico'),
    (r'\bpiscologicos\b', 'psicológicos'),
    (r'\bPiscologicos\b', 'Psicológicos'),
    (r'\bpiscologicas\b', 'psicológicas'),
    (r'\bPiscologicas\b', 'Psicológicas'),
    (r'\bspicologos\b', 'psicólogos'),
    (r'\bspicologia\b', 'psicología'),
    (r'\bspique\b', 'psique'),
    (r'\bpisque\b', 'psique'),
    (r'\bpiscosis\b', 'psicosis'),
    (r'\bsingiedad\b', 'ansiedad'),
    (r'\bsingedad\b', 'ansiedad'),
    (r'\bsinguiedad\b', 'ansiedad'),
    (r'\banisiedad\b', 'ansiedad'),
    (r'\bAnisiedad\b', 'Ansiedad'),
    (r'\bobesesion\b', 'obsesión'),
    (r'\bobesesivo\b', 'obsesivo'),
    (r'\bobesesivos\b', 'obsesivos'),
    (r'\bcerebo\b', 'cerebro'),
    (r'\bspicodinamico\b', 'psicodinámico'),
    (r'\bspicodinamica\b', 'psicodinámica'),
    (r'\bspicoanalisis\b', 'psicoanálisis'),
    (r'\bexpressarlo\b', 'expresarlo'),
    (r'\banunque\b', 'aunque'),
    (r'\bAnunque\b', 'Aunque'),
    (r'\brepressalia\b', 'represalia'),
    (r'\bcomprenison\b', 'comprensión'),
    (r'\bComprenison\b', 'Comprensión'),
    (r'\bescalva\b', 'esclava'),
    (r'\bconviriteran\b', 'convirtieran'),
    (r'\bconviritera\b', 'convirtiera'),
    (r'\bconvirette\b', 'conviértete'),
    (r'\bConvirette\b', 'Conviértete'),
    (r'\bproducucen\b', 'producen'),
    (r'\bimpaciales\b', 'imparciales'),
    (r'\bovidar\b', 'olvidar'),
    (r'\bsares superieores\b', 'seres superiores'),
    (r'\bposibilitades\b', 'posibilidades'),
    (r'\bintrosppeccion\b', 'introspección'),
    (r'\binteractias\b', 'interactúas'),
    (r'\bpresentza\b', 'presenta'),
    (r'\bcresen\b', 'crecen'),
    (r'\bcrescio\b', 'creció'),
    (r'\bjueegan\b', 'juegan'),
    (r'\bdesconcentado\b', 'desconcentrado'),
    (r'\bcontolar\b', 'controlar'),
    (r'\bcentralre\b', 'centrarse'),
    (r'\bcentralanose\b', 'centrándose'),
    (r'\bEscaere s\b', 'Escáneres'),
    (r'\bse seabe\b', 'se sabe'),
    (r'\bveecs\b', 'veces'),
    (r'\bsignificia\b', 'significa'),
    (r'\bsignificicar\b', 'significar'),
    (r'\binstitos\b', 'instintos'),
    (r'\binstitivas\b', 'instintivas'),
    (r'\bentrenraner\b', 'entrenar'),
    (r'\beticazmente\b', 'eficazmente'),
    (r'\bdesalntar\b', 'desalentar'),
    (r'\bcantiidad\b', 'cantidad'),
    (r'\bdifferencia\b', 'diferencia'),
    (r'\bdiffundiendo\b', 'difundiendo'),
    (r'\bdifficultad\b', 'dificultad'),
    (r'\bmodema\b', 'moderna'),
    (r'\bsentiminetos\b', 'sentimientos'),
    (r'\bsentiminento\b', 'sentimiento'),
    (r'\btransmisision\b', 'transmisión'),
    (r'\breccuadre\b', 'reencuadre'),
    (r'\bContentos\b', 'Contextos'),
    (r'\bcontentos\b', 'contextos'),
    (r'\bEjempllo\b', 'Ejemplo'),

    # 4. PALABRAS ESDRÚJULAS Y SOBREESDRÚJULAS
    (r'\bPsicologico\b', 'Psicológico'),
    (r'\bpsicologico\b', 'psicológico'),
    (r'\bPsicologica\b', 'Psicológica'),
    (r'\bpsicologica\b', 'psicológica'),
    (r'\bPsicologicos\b', 'Psicológicos'),
    (r'\bpsicologicos\b', 'psicológicos'),
    (r'\bPsicologicas\b', 'Psicológicas'),
    (r'\bpsicologicas\b', 'psicológicas'),
    (r'\bPsicologo\b', 'Psicólogo'),
    (r'\bpsicologo\b', 'psicólogo'),
    (r'\bPsicologos\b', 'Psicólogos'),
    (r'\bpsicologos\b', 'psicólogos'),
    (r'\bPsiquiatrico\b', 'Psiquiátrico'),
    (r'\bpsiquiatrico\b', 'psiquiátrico'),
    (r'\bCientifico\b', 'Científico'),
    (r'\bcientifico\b', 'científico'),
    (r'\bCientifica\b', 'Científica'),
    (r'\bcientifica\b', 'científica'),
    (r'\bCientificos\b', 'Científicos'),
    (r'\bcientificos\b', 'científicos'),
    (r'\bCientificas\b', 'Científicas'),
    (r'\bcientificas\b', 'científicas'),
    (r'\bBiologico\b', 'Biológico'),
    (r'\bbiologico\b', 'biológico'),
    (r'\bBiologica\b', 'Biológica'),
    (r'\bbiologica\b', 'biológica'),
    (r'\bBiologicos\b', 'Biológicos'),
    (r'\bbiologicos\b', 'biológicos'),
    (r'\bBiologicas\b', 'Biológicas'),
    (r'\bbiologicas\b', 'biológicas'),
    (r'\bQuimico\b', 'Químico'),
    (r'\bquimico\b', 'químico'),
    (r'\bQuimica\b', 'Química'),
    (r'\bquimica\b', 'química'),
    (r'\bQuimicos\b', 'Químicos'),
    (r'\bquimicos\b', 'químicos'),
    (r'\bQuimicas\b', 'Químicas'),
    (r'\bquimicas\b', 'químicas'),
    (r'\bFisico\b', 'Físico'),
    (r'\bfisico\b', 'físico'),
    (r'\bFisica\b', 'Física'),
    (r'\bfisica\b', 'física'),
    (r'\bFisicos\b', 'Físicos'),
    (r'\bfisicos\b', 'físicos'),
    (r'\bFisicas\b', 'Físicas'),
    (r'\bfisicas\b', 'físicas'),
    (r'\bTerapeutico\b', 'Terapéutico'),
    (r'\bterapeutico\b', 'terapéutico'),
    (r'\bTerapeutica\b', 'Terapéutica'),
    (r'\bterapeutica\b', 'terapéutica'),
    (r'\bTerapeuticos\b', 'Terapéuticos'),
    (r'\bterapeuticos\b', 'terapéuticos'),
    (r'\bTerapeuticas\b', 'Terapéuticas'),
    (r'\bterapeuticas\b', 'terapéuticas'),
    (r'\bFilosofico\b', 'Filosófico'),
    (r'\bfilosofico\b', 'filosófico'),
    (r'\bFilosofica\b', 'Filosófica'),
    (r'\bfilosofica\b', 'filosófica'),
    (r'\bFilosoficos\b', 'Filosóficos'),
    (r'\bfilosoficos\b', 'filosóficos'),
    (r'\bFilosoficas\b', 'Filosóficas'),
    (r'\bfilosoficas\b', 'filosóficas'),
    (r'\bJuridico\b', 'Jurídico'),
    (r'\bjuridico\b', 'jurídico'),
    (r'\bJuridica\b', 'Jurídica'),
    (r'\bjuridica\b', 'jurídica'),
    (r'\bJuridicamente\b', 'Jurídicamente'),
    (r'\bjuridicamente\b', 'jurídicamente'),
    (r'\bEstrategico\b', 'Estratégico'),
    (r'\bestrategico\b', 'estratégico'),
    (r'\bEstrategica\b', 'Estratégica'),
    (r'\bestrategica\b', 'estratégica'),
    (r'\bEstrategicos\b', 'Estratégicos'),
    (r'\bestrategicos\b', 'estratégicos'),
    (r'\bEstrategicas\b', 'Estratégicas'),
    (r'\bestrategicas\b', 'estratégicas'),
    (r'\bPractico\b', 'Práctico'),
    (r'\bpractico\b', 'práctico'),
    (r'\bPractica\b', 'Práctica'),
    (r'\bpractica\b', 'práctica'),
    (r'\bPracticos\b', 'Prácticos'),
    (r'\bpracticos\b', 'prácticos'),
    (r'\bPracticas\b', 'Prácticas'),
    (r'\bpracticas\b', 'prácticas'),
    (r'\bBasico\b', 'Básico'),
    (r'\bbasico\b', 'básico'),
    (r'\bBasica\b', 'Básica'),
    (r'\bbasica\b', 'básica'),
    (r'\bBasicos\b', 'Básicos'),
    (r'\bbasicos\b', 'básicos'),
    (r'\bBasicas\b', 'Básicas'),
    (r'\bbasicas\b', 'básicas'),
    (r'\bEspecifico\b', 'Específico'),
    (r'\bespecifico\b', 'específico'),
    (r'\bEspecifica\b', 'Específica'),
    (r'\bespecifica\b', 'específica'),
    (r'\bEspecificos\b', 'Específicos'),
    (r'\bespecificos\b', 'específicos'),
    (r'\bEspecificas\b', 'Específicas'),
    (r'\bespecificas\b', 'específicas'),
    (r'\bTeorico\b', 'Teórico'),
    (r'\bteorico\b', 'teórico'),
    (r'\bTeorica\b', 'Teórica'),
    (r'\bteorica\b', 'teórica'),
    (r'\bNeurologico\b', 'Neurológico'),
    (r'\bneurologico\b', 'neurológico'),
    (r'\bNeurologica\b', 'Neurológica'),
    (r'\bneurologica\b', 'neurológica'),
    (r'\bAutomatico\b', 'Automático'),
    (r'\bautomatico\b', 'automático'),
    (r'\bAutomatica\b', 'Automática'),
    (r'\bautomatica\b', 'automática'),
    (r'\bDinamico\b', 'Dinámico'),
    (r'\bdinamico\b', 'dinámico'),
    (r'\bDinamica\b', 'Dinámica'),
    (r'\bdinamica\b', 'dinámica'),
    (r'\bAntiguedad\b', 'Antigüedad'),
    (r'\bantiguedad\b', 'antigüedad'),
    (r'\bAmbito\b', 'Ámbito'),
    (r'\bambito\b', 'ámbito'),
    (r'\bAmbitos\b', 'Ámbitos'),
    (r'\bambitos\b', 'ámbitos'),
    (r'\bUnico\b', 'Único'),
    (r'\bunico\b', 'único'),
    (r'\bUnica\b', 'Única'),
    (r'\bunica\b', 'única'),
    (r'\bUnicos\b', 'Únicos'),
    (r'\bunicos\b', 'únicos'),
    (r'\bUnicas\b', 'Únicas'),
    (r'\bunicas\b', 'únicas'),
    (r'\bAutonomo\b', 'Autónomo'),
    (r'\bautonomo\b', 'autónomo'),
    (r'\bAutonoma\b', 'Autónoma'),
    (r'\bautonoma\b', 'autónoma'),
    (r'\bAutonomos\b', 'Autónomos'),
    (r'\bautonomos\b', 'autónomos'),
    (r'\bAutonomas\b', 'Autónomas'),
    (r'\bautonomas\b', 'autónomas'),
    (r'\bNumero\b', 'Número'),
    (r'\bnumero\b', 'número'),
    (r'\bNumeros\b', 'Números'),
    (r'\bnumeros\b', 'números'),
    (r'\bLimite\b', 'Límite'),
    (r'\blimite\b', 'límite'),
    (r'\bLimites\b', 'Límites'),
    (r'\blimites\b', 'límites'),
    (r'\bTactica\b', 'Táctica'),
    (r'\btactica\b', 'táctica'),
    (r'\bTacticas\b', 'Tácticas'),
    (r'\btacticas\b', 'tácticas'),
    (r'\bTactico\b', 'Táctico'),
    (r'\btactico\b', 'táctico'),
    (r'\bVictima\b', 'Víctima'),
    (r'\bvictima\b', 'víctima'),
    (r'\bVictimas\b', 'Víctimas'),
    (r'\bvictimas\b', 'víctimas'),
    (r'\bPagina\b', 'Página'),
    (r'\bpagina\b', 'página'),
    (r'\bPaginas\b', 'Páginas'),
    (r'\bpaginas\b', 'páginas'),
    (r'\bLinea\b', 'Línea'),
    (r'\blinea\b', 'línea'),
    (r'\bLineas\b', 'Líneas'),
    (r'\blineas\b', 'líneas'),
    (r'\bMetodo\b', 'Método'),
    (r'\bmetodo\b', 'método'),
    (r'\bMetodos\b', 'Métodos'),
    (r'\bmetodos\b', 'métodos'),
    (r'\bHabito\b', 'Hábito'),
    (r'\bhabito\b', 'hábito'),
    (r'\bHabitos\b', 'Hábitos'),
    (r'\bhabitos\b', 'hábitos'),
    (r'\bAnalisis\b', 'Análisis'),
    (r'\banalisis\b', 'análisis'),
    (r'\bExito\b', 'Éxito'),
    (r'\bexito\b', 'éxito'),
    (r'\bExitos\b', 'Éxitos'),
    (r'\bexitos\b', 'éxitos'),
    (r'\bEpoca\b', 'Época'),
    (r'\bepoca\b', 'época'),
    (r'\bEpocas\b', 'Épocas'),
    (r'\bepocas\b', 'épocas'),
    (r'\bUltimo\b', 'Último'),
    (r'\bultimo\b', 'último'),
    (r'\bUltima\b', 'Última'),
    (r'\bultima\b', 'última'),
    (r'\bUltimos\b', 'Últimos'),
    (r'\bultimos\b', 'últimos'),
    (r'\bUltimas\b', 'Últimas'),
    (r'\bultimas\b', 'últimas'),
    (r'\bUltimamente\b', 'Últimamente'),
    (r'\bultimamente\b', 'últimamente'),
    (r'\bValido\b', 'Válido'),
    (r'\bvalido\b', 'válido'),
    (r'\bValida\b', 'Válida'),
    (r'\bvalida\b', 'válida'),
    (r'\bSolido\b', 'Sólido'),
    (r'\bsolido\b', 'sólido'),
    (r'\bSolida\b', 'Sólida'),
    (r'\bsolida\b', 'sólida'),
    (r'\bLogica\b', 'Lógica'),
    (r'\blogica\b', 'lógica'),
    (r'\bLogico\b', 'Lógico'),
    (r'\blogico\b', 'lógico'),
    (r'\bLogicos\b', 'Lógicos'),
    (r'\blogicos\b', 'lógicos'),
    (r'\bLogicas\b', 'Lógicas'),
    (r'\blogicas\b', 'lógicas'),
    (r'\bRetorica\b', 'Retórica'),
    (r'\bretorica\b', 'retórica'),
    (r'\bEtica\b', 'Ética'),
    (r'\betica\b', 'ética'),
    (r'\bEtico\b', 'Ético'),
    (r'\betico\b', 'ético'),
    (r'\bHaptica\b', 'Háptica'),
    (r'\bhaptica\b', 'háptica'),
    (r'\bProposito\b', 'Propósito'),
    (r'\bproposito\b', 'propósito'),

    # 5. PALABRAS AGUDAS EN -ÓN / -IÓN
    (r'\bInformacion\b', 'Información'),
    (r'\binformacion\b', 'información'),
    (r'\bIntroduccion\b', 'Introducción'),
    (r'\bintroduccion\b', 'introducción'),
    (r'\bConclusion\b', 'Conclusión'),
    (r'\bconclusion\b', 'conclusión'),
    (r'\bPersuasion\b', 'Persuasión'),
    (r'\bpersuasion\b', 'persuasión'),
    (r'\bManipulacion\b', 'Manipulación'),
    (r'\bmanipulacion\b', 'manipulación'),
    (r'\bRelacion\b', 'Relación'),
    (r'\brelacion\b', 'relación'),
    (r'\bComunicacion\b', 'Comunicación'),
    (r'\bcomunicacion\b', 'comunicación'),
    (r'\bEmocion\b', 'Emoción'),
    (r'\bemocion\b', 'emoción'),
    (r'\bRegulacion\b', 'Regulación'),
    (r'\bregulacion\b', 'regulación'),
    (r'\bAtencion\b', 'Atención'),
    (r'\batencion\b', 'atención'),
    (r'\bIntencion\b', 'Intención'),
    (r'\bintencion\b', 'intención'),
    (r'\bConexion\b', 'Conexión'),
    (r'\bconexion\b', 'conexión'),
    (r'\bAfirmacion\b', 'Afirmación'),
    (r'\bafirmacion\b', 'afirmación'),
    (r'\bExposicion\b', 'Exposición'),
    (r'\bexposicion\b', 'exposición'),
    (r'\bReaccion\b', 'Reacción'),
    (r'\breaccion\b', 'reacción'),
    (r'\bSituacion\b', 'Situación'),
    (r'\bsituacion\b', 'situación'),
    (r'\bObservacion\b', 'Observación'),
    (r'\bobservacion\b', 'observación'),
    (r'\bExplicacion\b', 'Explicación'),
    (r'\bexplicacion\b', 'explicación'),
    (r'\bPrediccion\b', 'Predicción'),
    (r'\bprediccion\b', 'predicción'),
    (r'\bFuncion\b', 'Función'),
    (r'\bfuncion\b', 'función'),
    (r'\bPosicion\b', 'Posición'),
    (r'\bposicion\b', 'posición'),
    (r'\bCondicion\b', 'Condición'),
    (r'\bcondicion\b', 'condición'),
    (r'\bAccion\b', 'Acción'),
    (r'\baccion\b', 'acción'),
    (r'\bPresion\b', 'Presión'),
    (r'\bpresion\b', 'presión'),
    (r'\bTension\b', 'Tensión'),
    (r'\btension\b', 'tensión'),
    (r'\bDepresion\b', 'Depresión'),
    (r'\bdepresion\b', 'depresión'),
    (r'\bCompasion\b', 'Compasión'),
    (r'\bcompasion\b', 'compasión'),
    (r'\bObsesion\b', 'Obsesión'),
    (r'\bobsesion\b', 'obsesión'),
    (r'\bDisociacion\b', 'Disociación'),
    (r'\bdisociacion\b', 'disociación'),
    (r'\bDistraccion\b', 'Distracción'),
    (r'\bdistraccion\b', 'distracción'),
    (r'\bInteraccion\b', 'Interacción'),
    (r'\binteraccion\b', 'interacción'),
    (r'\bSensacion\b', 'Sensación'),
    (r'\bsensacion\b', 'sensación'),
    (r'\bPercepcion\b', 'Percepción'),
    (r'\bpercepcion\b', 'percepción'),
    (r'\bFormacion\b', 'Formación'),
    (r'\bformacion\b', 'formación'),
    (r'\bProcrastinacion\b', 'Procrastinación'),
    (r'\bprocrastinacion\b', 'procrastinación'),
    (r'\bConversacion\b', 'Conversación'),
    (r'\bconversacion\b', 'conversación'),
    (r'\bAprobacion\b', 'Aprobación'),
    (r'\baprobacion\b', 'aprobación'),
    (r'\bExperimentacion\b', 'Experimentación'),
    (r'\bexperimentacion\b', 'experimentación'),
    (r'\bAsociacion\b', 'Asociación'),
    (r'\basociacion\b', 'asociación'),
    (r'\bDeclaracion\b', 'Declaración'),
    (r'\bdeclaracion\b', 'declaración'),
    (r'\bReproduccion\b', 'Reproducción'),
    (r'\breproduccion\b', 'reproducción'),
    (r'\bDuplicacion\b', 'Duplicación'),
    (r'\bduplicacion\b', 'duplicación'),
    (r'\bTransmision\b', 'Transmisión'),
    (r'\btransmision\b', 'transmisión'),
    (r'\bEvolucion\b', 'Evolución'),
    (r'\bevolucion\b', 'evolución'),
    (r'\bIntrospeccion\b', 'Introspección'),
    (r'\bintrospeccion\b', 'introspección'),
    (r'\bRespiracion\b', 'Respiración'),
    (r'\brespiracion\b', 'respiración'),
    (r'\bProgramacion\b', 'Programación'),
    (r'\bprogramacion\b', 'programación'),
    (r'\bAproximacion\b', 'Aproximación'),
    (r'\baproximacion\b', 'aproximación'),
    (r'\bIdealizacion\b', 'Idealización'),
    (r'\bidealizacion\b', 'idealización'),
    (r'\bDevaluacion\b', 'Devaluación'),
    (r'\bdevaluacion\b', 'devaluación'),
    (r'\bRecuperacion\b', 'Recuperación'),
    (r'\brecuperacion\b', 'recuperación'),
    (r'\bCorazon\b', 'Corazón'),
    (r'\bcorazon\b', 'corazón'),
    (r'\bPatron\b', 'Patrón'),
    (r'\bpatron\b', 'patrón'),
    (r'\bRazon\b', 'Razón'),
    (r'\brazon\b', 'razón'),
    (r'\bDecision\b', 'Decisión'),
    (r'\bdecision\b', 'decisión'),

    # 6. HIATOS Y PALABRAS TERMINADAS EN -ÍA / -ÍAS
    (r'\bFilosofia\b', 'Filosofía'),
    (r'\bfilosofia\b', 'filosofía'),
    (r'\bTeoria\b', 'Teoría'),
    (r'\bteoria\b', 'teoría'),
    (r'\bTeorias\b', 'Teorías'),
    (r'\bteorias\b', 'teorías'),
    (r'\bTecnologia\b', 'Tecnología'),
    (r'\btecnologia\b', 'tecnología'),
    (r'\bTecnologias\b', 'Tecnologías'),
    (r'\btecnologias\b', 'tecnologías'),
    (r'\bEmpatia\b', 'Empatía'),
    (r'\bempatia\b', 'empatía'),
    (r'\bEnergia\b', 'Energía'),
    (r'\benergia\b', 'energía'),
    (r'\bSimpatia\b', 'Simpatía'),
    (r'\bsimpatia\b', 'simpatía'),
    (r'\bMayoria\b', 'Mayoría'),
    (r'\bmayoria\b', 'mayoría'),
    (r'\bGuia\b', 'Guía'),
    (r'\bguia\b', 'guía'),
    (r'\bGuias\b', 'Guías'),
    (r'\bguias\b', 'guías'),
    (r'\bAlegria\b', 'Alegría'),
    (r'\balegria\b', 'alegría'),
    (r'\bFantasia\b', 'Fantasía'),
    (r'\bfantasia\b', 'fantasía'),
    (r'\bFantasias\b', 'Fantasías'),
    (r'\bfantasias\b', 'fantasías'),
    (r'\bArmonia\b', 'Armonía'),
    (r'\barmonia\b', 'armonía'),
    (r'\bAutonomia\b', 'Autonomía'),
    (r'\bautonomia\b', 'autonomía'),
    (r'\bJerarquia\b', 'Jerarquía'),
    (r'\bjerarquia\b', 'jerarquía'),
    (r'\bCategoria\b', 'Categoría'),
    (r'\bcategoria\b', 'categoría'),
    (r'\bCategorias\b', 'Categorías'),
    (r'\bcategorias\b', 'categorías'),
    (r'\bEstrategia\b', 'Estrategia'),
    (r'\bestrategia\b', 'estrategia'),
    (r'\bEstrategias\b', 'Estrategias'),
    (r'\bestrategias\b', 'estrategias'),
    (r'\bpodria\b', 'podría'),
    (r'\bPodria\b', 'Podría'),
    (r'\bpodrian\b', 'podrían'),
    (r'\bPodrian\b', 'Podrían'),
    (r'\bdeberia\b', 'debería'),
    (r'\bDeberia\b', 'Debería'),
    (r'\bdeberian\b', 'deberían'),
    (r'\bDeberian\b', 'Deberían'),
    (r'\btendria\b', 'tendría'),
    (r'\bTendria\b', 'Tendría'),
    (r'\btendrian\b', 'tendrían'),
    (r'\bTendrian\b', 'Tendrían'),
    (r'\bhabria\b', 'habría'),
    (r'\bHabria\b', 'Habría'),
    (r'\bhabrian\b', 'habrían'),
    (r'\btenia\b', 'tenía'),
    (r'\bTenia\b', 'Tenía'),
    (r'\btenian\b', 'tenían'),
    (r'\bTenian\b', 'Tenían'),
    (r'\bsabia\b', 'sabía'),
    (r'\bSabia\b', 'Sabía'),
    (r'\bsabian\b', 'sabían'),
    (r'\bSabian\b', 'Sabían'),
    (r'\bqueria\b', 'quería'),
    (r'\bQueria\b', 'Quería'),
    (r'\bquerian\b', 'querían'),
    (r'\bhacia\b', 'hacía'),
    (r'\bHacia\b', 'Hacía'),
    (r'\bdecia\b', 'decía'),
    (r'\bDecia\b', 'Decía'),
    (r'\bexistia\b', 'existía'),
    (r'\bExistia\b', 'Existía'),

    # 7. ADVERBIOS, VERBOS EN PASADO / FUTURO Y COMUNES
    (r'\bTambien\b', 'También'),
    (r'\btambien\b', 'también'),
    (r'\bAdemas\b', 'Además'),
    (r'\bademas\b', 'además'),
    (r'\bDespues\b', 'Después'),
    (r'\bdespues\b', 'después'),
    (r'\bQuiza\b', 'Quizá'),
    (r'\bquiza\b', 'quizá'),
    (r'\bQuizas\b', 'Quizás'),
    (r'\bquizas\b', 'quizás'),
    (r'\bAqui\b', 'Aquí'),
    (r'\baqui\b', 'aquí'),
    (r'\bAlli\b', 'Allí'),
    (r'\balli\b', 'allí'),
    (r'\bAlla\b', 'Allá'),
    (r'\balla\b', 'allá'),
    (r'\bAsi\b', 'Así'),
    (r'\basi\b', 'así'),
    (r'\bFacil\b', 'Fácil'),
    (r'\bfacil\b', 'fácil'),
    (r'\bFacilmente\b', 'Fácilmente'),
    (r'\bfacilmente\b', 'fácilmente'),
    (r'\bDificil\b', 'Difícil'),
    (r'\bdificil\b', 'difícil'),
    (r'\bDificilmente\b', 'Difícilmente'),
    (r'\bdificilmente\b', 'difícilmente'),
    (r'\bUtil\b', 'Útil'),
    (r'\butil\b', 'útil'),
    (r'\bUtiles\b', 'Útiles'),
    (r'\butiles\b', 'útiles'),
    (r'\bcomenzo\b', 'comenzó'),
    (r'\bComenzo\b', 'Comenzó'),
    (r'\bdescubrio\b', 'descubrió'),
    (r'\bDescubrio\b', 'Descubrió'),
    (r'\bconvirtio\b', 'convirtió'),
    (r'\bConvirtio\b', 'Convirtió'),
    (r'\bescribio\b', 'escribió'),
    (r'\bEscribio\b', 'Escribió'),
    (r'\babordo\b', 'abordó'),
    (r'\bAbordo\b', 'Abordó'),
    (r'\bdeclaro\b', 'declaró'),
    (r'\bDeclaro\b', 'Declaró'),
    (r'\bdetermino\b', 'determinó'),
    (r'\bDetermino\b', 'Determinó'),
    (r'\bafirmo\b', 'afirmó'),
    (r'\bAfirmo\b', 'Afirmó'),
    (r'\breconocio\b', 'reconoció'),
    (r'\bReconocio\b', 'Reconoció'),
    (r'\badquirio\b', 'adquirió'),
    (r'\bconsiguio\b', 'consiguió'),
    (r'\bsurgio\b', 'surgió'),
    (r'\bSurgio\b', 'Surgió'),
    (r'\bpublico\b', 'publicó'),
    (r'\bfundo\b', 'fundó'),
    (r'\bexplico\b', 'explicó'),
    (r'\brevelo\b', 'reveló'),
    (r'\bnacio\b', 'nació'),
    (r'\bpodra\b', 'podrá'),
    (r'\bPodra\b', 'Podrá'),
    (r'\bpodras\b', 'podrás'),
    (r'\bPodras\b', 'Podrás'),
    (r'\bpodran\b', 'podrán'),
    (r'\bPodran\b', 'Podrán'),
    (r'\btendra\b', 'tendrá'),
    (r'\bTendra\b', 'Tendrá'),
    (r'\btendras\b', 'tendrás'),
    (r'\btendran\b', 'tendrán'),
    (r'\bvera\b', 'verá'),
    (r'\bVera\b', 'Verá'),
    (r'\bveras\b', 'verás'),
    (r'\bVeras\b', 'Verás'),
    (r'\bveran\b', 'verán'),
    (r'\baprendera\b', 'aprenderá'),
    (r'\baprenderas\b', 'aprenderás'),
    (r'\baprenderan\b', 'aprenderán'),
    (r'\bobtendra\b', 'obtendrá'),
    (r'\bObtendra\b', 'Obtendrá'),
    (r'\bobtendras\b', 'obtendrás'),
    (r'\bobtendran\b', 'obtendrán'),
    (r'\bguiara\b', 'guiará'),
    (r'\bhara\b', 'hará'),
    (r'\bHara\b', 'Hará'),
    (r'\bharas\b', 'harás'),
    (r'\bharan\b', 'harán'),
    (r'\bestara\b', 'estará'),
    (r'\bEstara\b', 'Estará'),
    (r'\bestaran\b', 'estarán'),
    (r'\bsera\b', 'será'),
    (r'\bSera\b', 'Será'),
    (r'\bseran\b', 'serán'),
    (r'\bestan\b', 'están'),
    (r'\bEstan\b', 'Están'),
    (r'\bmas\b', 'más'),
    (r'\bMas\b', 'Más'),

    # 8. BASURA OCR Y MATEMÁTICA
    (r'\[MISSING_PAGE_FAIL:\d+\]', ''),
    (r'\\\({}_{i}\\\)', '¡'),
    (r'\\\({}^{\\rm VI}\\\)', 'VI'),
    (r'\\\(\\underline{\\iota}\\\)', '¿'),
    (r'\?{2,}', '¿'),
    (r'\?Se ha preguntado', '¿Se ha preguntado'),
    (r'\?que ocurre', '¿qué ocurre'),
    (r'\?O que les hace', '¿O qué les hace'),
    (r'\?Qué\b', '¿Qué'),
    (r'\?Por qué\b', '¿Por qué'),
    (r'\?Cómo\b', '¿Cómo'),
    (r'\?Cuándo\b', '¿Cuándo'),
    (r'\?Quién\b', '¿Quién'),
    (r'igracias', '¡Gracias'),
    (r'iEnhorabuena', '¡Enhorabuena'),
    (r'iFelicidades', '¡Felicidades')
]

def clean_and_format_markdown(text):
    for pat, rep in RULES:
        text = re.sub(pat, rep, text)
    
    text = re.sub(r'\n*\*\*Cap[ií]tulo\s*(\d+)\s*:\s*(.*?)\*\*\n*', r'\n\n## 📖 Capítulo \1: \2\n\n', text, flags=re.IGNORECASE)
    text = re.sub(r'\n*##\s*Cap[ií]tulo\s*(\d+)\s*:\s*(.*?)\n*', r'\n\n## 📖 Capítulo \1: \2\n\n', text, flags=re.IGNORECASE)
    
    text = re.sub(r'([^\n])\n(#{1,4}\s+[^\n]+)', r'\1\n\n\2', text)
    text = re.sub(r'(#{1,4}\s+[^\n]+)\n([^\n#])', r'\1\n\n\2', text)
    
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

# PROCESAR LOS 76 ARCHIVOS
files = [f for f in os.listdir(MD_DIR) if f.endswith('.md')]
files.sort()

cleaned_corpus = {}
total_chars = 0

for i, f in enumerate(files):
    path = os.path.join(MD_DIR, f)
    with open(path, 'r', encoding='utf-8') as fh:
        raw = fh.read()
    
    cleaned = clean_and_format_markdown(raw)
    
    with open(path, 'w', encoding='utf-8') as out_fh:
        out_fh.write(cleaned)
    
    key = f.replace('.md', '')
    cleaned_corpus[key] = cleaned
    total_chars += len(cleaned)
    print(f"[{i+1:02d}/76] OK: {f} depurado ({len(cleaned):,} caracteres)")

# RECOMPILAR JS/BOOK_CONTENT.JS
js_code = "var BOOK_CONTENT = " + json.dumps(cleaned_corpus, ensure_ascii=False) + ";\nwindow.BOOK_CONTENT = BOOK_CONTENT;\n"
with open(BOOK_JS, 'w', encoding='utf-8') as f:
    f.write(js_code)

print(f"\nRECONSTRUCCION FINALIZADA CON EXITO!")
print(f"Archivos sobreescritos y depurados en: {MD_DIR}/")
print(f"Compilado global {BOOK_JS} actualizado ({total_chars:,} caracteres totales procesados).")
